env:

steps:
  - label: ":golangci-lint: lint :lint-roller:"
    key: "lint"
    plugins:
      - docker#v5.3.0:
          image: "registry.hub.docker.com/golangci/golangci-lint:v1.50"
          command: ["golangci-lint", "run", "-v"]

  - label: ":test_tube: test"
    key: "test"
    plugins:
      - docker#v5.3.0:
          image: "golang:1.19"
          command: ["go", "test", "-cover" ,"-race", "./..."]

  - label: ":golang: build"
    key: "gobuild"
    artifact_paths: "bin/${APP_NAME}"
    plugins:
      - docker#v5.3.0:
          image: "golang:1.19"
          environment:
            - "APP_NAME=${BUILDKITE_PIPELINE_SLUG}"
          command: ["go", "build", "-mod=mod", "-a", "-o", "bin/$APP_NAME"]
